### ISSUE TITLE
Sometimes I cannot save query because of lost mapping

### ISSUE THREAD

**Issue by przepompownia** [kristijanhusak/vim-dadbod-ui#72]
I noticed that my current query buffer has the default mapping `<Leader>W` to abstract `<Plug>(DBUI_SaveQuery)` but it lost mapping from  `<Plug>(DBUI_SaveQuery)` to the real action. Not all local mapping are lost:
![image](https://user-images.githubusercontent.com/11404453/100632812-928a1580-332d-11eb-89ef-f1d3305c2dd2.png)

**Comment by kristijanhusak** [comment]
I'm not sure I understand. What you mean by this?
> but it lost mapping from <Plug>(DBUI_SaveQuery) to the real action

what is a real action?

**Comment by przepompownia** [comment]
I meant the command abstract map points to: `:call <SNR>185_method('save_query')<CR>`
![image](https://user-images.githubusercontent.com/11404453/100670076-a7cb6800-335e-11eb-914a-dbfdddb4e51b.png)

**Comment by kristijanhusak** [comment]
Plug map points to the function call, and `,W` points to the plug mapping. What's wrong in that?

**Comment by przepompownia** [comment]
Nothing wrong: the second image comes from the fresh running `DBUI` where mapping still exists. The first one illustrates the problem. 

Maybe I can send you some additional information that can help.

**Comment by kristijanhusak** [comment]
Ok, I get it. `<Plug>(DBUI_SaveQuery)` is not attached when viewing already saved query. It is available only for "new" queries. Would you expect it to work also for saved queries, or not to bind `,W` when it is not available?

**Comment by przepompownia** [comment]
Independently of this bug ("keyboard->abstract" mapping is available also when "abstract->real" not) I would like to can save such query once again. We could then overwrite existing query, so the new filename (the old name by default) would be possible to edit in the save dialog.

On the other side, there is no problem to do it at the Vim level. With the recent fixes manually saved query buffers seems to behave in the same way as auto-generated query buffer (it require more tests to ensure).

**Comment by kristijanhusak** [comment]
I pushed a fix ~30 min ago that binds the mapping if you use custom `g:db_ui_tmp_query_location`. I guess we could always have the mapping.

**Comment by przepompownia** [comment]
OK, I pulled this change to observe if the mapping will be then more persistent.

**Comment by kristijanhusak** [comment]
Ok, let me know if you see anything strange.

**Comment by przepompownia** [comment]
The problem still exists when I try to load saved query buffer that is loaded (for example) before start DBUI. Please run:
```vim
badd path/to/saved/query/buffer
DBUI
```
It occurs after load vim session with such buffer.

**Comment by przepompownia** [comment]
`bwipeout` on such query buffer can be a workaround at the moment.

**Comment by przepompownia** [comment]
Filetype is not recognized. Instead of `bwipeout` we can `set ft=sql` and DBUI is able to execute the query again. 

Why not to add `sql` file extension (to any DBUI buffer file) by default (independently of the way of setting filetype)?

**Comment by kristijanhusak** [comment]
> The problem still exists when I try to load (from the drawer) any saved query buffer that was loaded before DBUI started. Please run:
> 
> ```viml
> badd path/to/saved/query/buffer
> DBUI
> ```
> 
> It occurs after load vim session with such buffer.

What happens if you do `:DBUIFindBuffer` after this?

**Comment by przepompownia** [comment]
```vim
badd path/to/saved/query/buffer
DBUI
wincmd w
b 2
```
From this point I have two scenarios: with
```vim
DBUIFindBuffer
```
the buffer appears on Buffers list (named as its saved equivalent), but I have still not populated saved queries list (0 items, opening/closing does not refresh the list, all saved queries on the buffer list are displayed). After opening the buffer from Buffers list the query  has still no `sql` filetype. 

With opening database view in the drawer first, saved queries list is populated, but the rest is the same. The buffer behaves as non-sql buffer.

**Comment by kristijanhusak** [comment]
I pushed some updates for DBUIFindBuffer. This was improved/fixed:

1. SQL filetype is automatically set if file is not `*.sql` file.
2. It automatically detects the database it needs to belong to, if buffer is a file in the folder of saved queries, no prompts like before.
3. Autocmd for automatically execute on save is properly attached.

Please give it a test and let me know how it looks now.

**Comment by przepompownia** [comment]
Preloaded buffers after unhiding it by the action on drawer or re-associating with DBUI by `:DBUIFindBuffer` are now usable as expected. It seems unlikely I will encounter a similar problem so we can close this issue and possibly open any new. 

Thanks for investingating this behaviour.

**Comment by przepompownia** [comment]
I missed one thing that was not fixed: the buffer activated with `:DBUIFindBuffer` is shown on `Buffers` list. Saved queries list and tables list still remain empty and even impossible to populate by keyboard action.

**Comment by kristijanhusak** [comment]
Should be fixed now. You can always redraw the current database by pressing `R` while cursor is inside the database tree. This is now done automatically.

**Comment by przepompownia** [comment]
Confirmed :tada:
